name: Deploy to Render

on:
  push:
    branches:
      - main  # O la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Notificar a Render para hacer el deploy
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
